version = 1

test_patterns = ["test/*.e2e-spec.ts"]

exclude_patterns = [
  "node_modules/**",
  "public/**",
  "dist/**"
]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "browser"
  ]